version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5433:5433"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  node_app_1:
    container_name: node_app_1
    build: ./Marketer-Server
    ports:
      - "3000:3000"
    volumes: 
      - ./Marketer-Server:/app
    depends_on:
      - node_db
      - kafka
  node_app_2:
    container_name: node_app_2
    build: ./Customer-Server
    ports:
      - "3001:3000"
    volumes: 
      - ./Customer-Server:/app
    depends_on:
      - node_db
      - kafka